# Generated by Django 4.0.4 on 2022-08-21 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity_manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitymanager',
            name='academic_degree',
            field=models.CharField(blank=True, choices=[('L', 'Licenciatura'), ('M', 'Maestria'), ('D', 'Doctorado')], max_length=1, null=True),
        ),
    ]
