# Generated by Django 4.0.4 on 2022-06-02 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('representative', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='representative',
            name='email',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Correo'),
        ),
    ]
