# Generated by Django 4.0.4 on 2022-09-12 06:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0002_organizationalunit_alter_university_email_and_more'),
        ('representative', '0003_representative_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='representative',
            name='origin_organizational_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='university.organizationalunit'),
        ),
        migrations.AddField(
            model_name='representative',
            name='origin_university',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='university.university'),
        ),
    ]
