# Generated by Django 4.0.4 on 2022-08-21 18:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Deadline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_edition', models.DateTimeField(default=2022)),
                ('date_to_upload_activities', models.DateTimeField(default=datetime.datetime(2022, 8, 21, 12, 51, 33, 471472))),
                ('date_to_upload_evidence', models.DateTimeField(default=datetime.datetime(2022, 8, 21, 12, 51, 33, 471486))),
                ('date_to_validate_evidence', models.DateTimeField(default=datetime.datetime(2022, 8, 21, 12, 51, 33, 471497))),
                ('date_edition_start', models.DateTimeField(default=datetime.datetime(2022, 8, 21, 12, 51, 33, 471509))),
                ('end_date_of_the_edition', models.DateTimeField(default=datetime.datetime(2022, 8, 21, 12, 51, 33, 471518))),
            ],
        ),
    ]
