# Generated by Django 4.0.4 on 2022-09-12 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deadline', '0003_alter_deadline_date_edition_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deadline',
            name='name_edition',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Nombre de la edicion'),
        ),
    ]
