# Generated by Django 4.0.4 on 2022-09-25 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deadline', '0004_deadline_name_edition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deadline',
            name='date_edition_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='deadline',
            name='date_to_upload_activities',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='deadline',
            name='date_to_upload_evidence',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='deadline',
            name='date_to_validate_evidence',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='deadline',
            name='end_date_of_the_edition',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
