# Generated by Django 4.0.4 on 2022-09-25 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deadline', '0005_alter_deadline_date_edition_start_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deadline',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
        migrations.AddField(
            model_name='deadline',
            name='status',
            field=models.BooleanField(default=True, verbose_name='Estatus'),
        ),
    ]
