# Generated by Django 4.0.4 on 2024-01-23 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deadline', '0006_deadline_is_active_deadline_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='deadline',
            name='file',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deadline',
            name='file_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='deadline',
            name='date_edition',
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AlterField(
            model_name='deadline',
            name='date_edition_start',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='deadline',
            name='date_to_upload_activities',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='deadline',
            name='date_to_upload_evidence',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='deadline',
            name='date_to_validate_evidence',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='deadline',
            name='end_date_of_the_edition',
            field=models.DateField(blank=True, null=True),
        ),
    ]
