# Generated by Django 4.0.4 on 2022-06-02 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reviewer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Nombre')),
                ('last_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Apellido')),
                ('user_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Usuario')),
                ('email', models.CharField(blank=True, max_length=50, null=True, verbose_name='Correo')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('status', models.BooleanField(default=True, verbose_name='Estatus')),
            ],
        ),
    ]
