# Generated by Django 4.0.4 on 2022-09-12 06:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0003_university_acronym'),
        ('reviewer', '0002_reviewer_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewer',
            name='origin_organizational_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='university.organizationalunit'),
        ),
        migrations.AddField(
            model_name='reviewer',
            name='origin_university',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='university.university'),
        ),
    ]
