# Generated by Django 4.0.4 on 2022-11-08 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviewer', '0003_reviewer_origin_organizational_unit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewer',
            name='global_reviewer',
            field=models.BooleanField(default=False, verbose_name='Revisor general'),
        ),
        migrations.AddField(
            model_name='reviewer',
            name='region',
            field=models.CharField(blank=True, choices=[('N', 'Norte'), ('CN', 'Centro Norte'), ('C', 'Centro'), ('S', 'Sur')], max_length=2, null=True),
        ),
    ]
