# Generated by Django 4.0.4 on 2022-06-06 23:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0001_initial'),
        ('presenter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='presenter',
            name='if_belong_to_school',
            field=models.BooleanField(default=True, verbose_name='Pertenece a un colegio'),
        ),
        migrations.AddField(
            model_name='presenter',
            name='origin_institution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='university.university'),
        ),
        migrations.CreateModel(
            name='Evidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curriculum_vitae', models.CharField(blank=True, max_length=50, null=True, verbose_name='Curriculum vitae')),
                ('presentation', models.CharField(blank=True, max_length=50, null=True, verbose_name='Presentacion')),
                ('list_attendance', models.CharField(blank=True, max_length=50, null=True, verbose_name='Lista de asistencia')),
                ('photos', models.CharField(blank=True, max_length=50, null=True, verbose_name='Fotos del evento')),
                ('presenter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='presenter.presenter')),
            ],
        ),
    ]
