# Generated by Django 4.0.4 on 2022-08-13 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0001_initial'),
        ('presenter', '0002_presenter_if_belong_to_school_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deadline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_edition', models.DateTimeField(default=2022)),
                ('date_to_upload_activities', models.DateTimeField()),
                ('date_to_upload_evidence', models.DateTimeField()),
                ('date_to_validate_evidence', models.DateTimeField()),
            ],
        ),
        migrations.AddField(
            model_name='presenter',
            name='activity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='activity.activity'),
        ),
    ]
