# Generated by Django 4.0.4 on 2022-08-21 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('presenter', '0003_deadline_presenter_activity'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Deadline',
        ),
        migrations.RemoveField(
            model_name='presenter',
            name='activity',
        ),
        migrations.DeleteModel(
            name='Evidence',
        ),
    ]
