# Generated by Django 4.0.4 on 2022-09-25 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0004_organizationalunit_acronym'),
        ('presenter', '0005_presenter_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='presenter',
            old_name='origin_institution',
            new_name='origin_university',
        ),
        migrations.AddField(
            model_name='presenter',
            name='origin_organizational_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='university.organizationalunit'),
        ),
        migrations.AddField(
            model_name='presenter',
            name='user_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Usuario'),
        ),
        migrations.AlterField(
            model_name='presenter',
            name='if_belong_to_school',
            field=models.BooleanField(default=True, verbose_name='Pertenece a la misma unidad academica/organizacional'),
        ),
    ]
