# Generated by Django 4.0.4 on 2022-10-28 14:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('presenter', '0006_rename_origin_institution_presenter_origin_university_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='presenter',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='presenter',
            name='position_institution',
            field=models.CharField(choices=[('1', 'Estudiante'), ('2', 'Maestro'), ('3', 'Director'), ('4', 'Personal de confianza'), ('5', 'Externo')], default='1', max_length=2),
        ),
    ]
