# Generated by Django 4.0.4 on 2022-10-31 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('presenter', '0007_presenter_created_by_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='presenter',
            options={'ordering': ('first_name', 'last_name')},
        ),
    ]
