# Generated by Django 4.0.4 on 2022-08-21 18:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presenter', '0005_presenter_user'),
        ('activity', '0002_deadline_typeevidence_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Deadline',
        ),
        migrations.AlterField(
            model_name='activity',
            name='co_presenter',
            field=models.ManyToManyField(blank=True, null=True, related_name='co_presenter', to='presenter.presenter'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='date_activity',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 21, 12, 51, 33, 435394)),
        ),
    ]
