# Generated by Django 4.0.4 on 2022-08-23 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0004_alter_activity_date_activity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='date_activity',
            field=models.DateTimeField(blank=True),
        ),
    ]
