# Generated by Django 4.0.4 on 2022-10-15 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0007_alter_activity_co_presenter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='activity_manager',
        ),
    ]
