# Generated by Django 4.0.4 on 2022-10-26 03:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('representative', '0005_alter_representative_origin_university'),
        ('activity', '0008_remove_activity_activity_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='representative.representative'),
        ),
    ]
