# Generated by Django 4.0.4 on 2022-10-31 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0010_alter_activity_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='type_of_public',
            field=models.CharField(blank=True, choices=[('INT', 'Interno'), ('EXT', 'Externo')], max_length=6, null=True),
        ),
    ]
