# Generated by Django 4.0.4 on 2022-11-08 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0011_activity_type_of_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='typeevidence',
            name='type',
            field=models.CharField(blank=True, choices=[('PDF', 'PDF'), ('URL', 'URL')], max_length=6, null=True),
        ),
    ]
