# Generated by Django 4.0.4 on 2022-11-11 06:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0012_typeevidence_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='evidence',
            options={},
        ),
        migrations.AlterField(
            model_name='evidence',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_evidences', to='activity.activity', verbose_name='Actividad'),
        ),
        migrations.AlterUniqueTogether(
            name='evidence',
            unique_together={('activity', 'type_evidence')},
        ),
    ]
