# Generated by Django 4.0.4 on 2022-11-12 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0013_alter_evidence_options_alter_evidence_activity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='typeevidence',
            name='evidence_status',
            field=models.CharField(choices=[('SEND', 'Subido'), ('DUE', 'Pendiente'), ('REJECT', 'Rechazado'), ('OK', 'Aprobado')], default='DUE', max_length=6, null=True),
        ),
    ]
