# Generated by Django 4.0.4 on 2022-11-12 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0014_typeevidence_evidence_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='typeevidence',
            name='evidence_status',
        ),
        migrations.AddField(
            model_name='evidence',
            name='evidence_status',
            field=models.CharField(choices=[('SEND', 'Subido'), ('DUE', 'Pendiente'), ('REJECT', 'Rechazado'), ('OK', 'Aprobado')], default='DUE', max_length=6, null=True),
        ),
    ]
