# Generated by Django 4.0.4 on 2022-11-15 03:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0016_evidence_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evidence',
            name='activity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_evidences', to='activity.activity', verbose_name='Actividad'),
        ),
        migrations.AlterField(
            model_name='evidence',
            name='type_evidence',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='activity.typeevidence'),
        ),
    ]
