# Generated by Django 4.0.4 on 2022-11-28 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0017_alter_evidence_activity_alter_evidence_type_evidence'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='activity_status',
            field=models.CharField(choices=[('DUE', 'Pendiente'), ('REJECT', 'Rechazado'), ('OK', 'Aprobado')], default='DUE', max_length=6, null=True),
        ),
    ]
