# Generated by Django 4.0.4 on 2022-11-29 03:31

import activity.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0018_activity_activity_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='certificate_file',
            field=models.FileField(blank=True, null=True, upload_to=activity.models.upload_certificate_file, verbose_name='Archivo'),
        ),
    ]
