# Generated by Django 4.0.4 on 2022-11-30 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0019_activity_certificate_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='evidence',
            name='observation',
            field=models.CharField(blank=True, max_length=1500, null=True, verbose_name='Observación'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='activity_status',
            field=models.CharField(choices=[('DUE', 'Pendiente'), ('INC', 'Incompleto'), ('REJECT', 'Rechazado'), ('OK', 'Aprobado')], default='DUE', max_length=6, null=True),
        ),
    ]
