# Generated by Django 4.0.4 on 2022-11-30 04:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('activity', '0021_alter_evidence_evidence_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='evidence',
            name='status_changed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_evidence_status_changed_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='evidence',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_evidence_created_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
