# Generated by Django 4.0.4 on 2022-12-13 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0022_evidence_status_changed_by_alter_evidence_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='typeactivity',
            name='title',
            field=models.CharField(blank=True, max_length=800, null=True, verbose_name='Titulo'),
        ),
    ]
