# Generated by Django 4.0.4 on 2022-12-13 01:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('presenter', '0008_alter_presenter_options'),
        ('activity', '0023_typeactivity_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='presenter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activity_presenter', to='presenter.presenter'),
        ),
    ]
