# Generated by Django 4.0.4 on 2023-08-31 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0024_alter_activity_presenter'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='edition',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]