# Generated by Django 4.0.4 on 2023-09-08 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0025_activity_edition'),
    ]

    operations = [
        migrations.AddField(
            model_name='typeactivity',
            name='maxCopresenter',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Maximo de copresentadores'),
        ),
    ]