# Generated by Django 4.0.4 on 2024-01-23 18:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('presenter', '0009_presenter_curp'),
        ('deadline', '0007_deadline_file_deadline_file_name_and_more'),
        ('activity', '0026_typeactivity_maxcopresenter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='area_knowledge',
            field=models.CharField(choices=[('I', 'I. Físico-Matemáticas y Ciencias de la Tierra'), ('II', 'II. Biología y Química'), ('III', 'III. Medicina y Ciencias de la Salud'), ('IV', 'IV. Ciencias de la Conducta y la Educación'), ('V', 'V. Humanidades'), ('VI', 'VI. Ciencias Sociales'), ('VII', 'VII. Ciencias de la Agricultura, Agropecuarias, Forestales y de Ecosistemas'), ('VIII', 'VIII. Ingenierías y Desarrollo Tecnológico'), ('IX', 'IX. Investigación Multidisciplinaria')], max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='edition',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='deadline.deadline'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='presenter',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='activity_presenter', to='presenter.presenter'),
        ),
    ]
