# Generated by Django 4.0.4 on 2025-01-30 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0028_alter_activity_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='modality',
            field=models.CharField(blank=True, choices=[('V', 'Virtual'), ('P', 'Presencial'), ('H', 'Hibrida (Virtual y Presencial)')], max_length=1, null=True),
        ),
    ]
