# Generated by Django 4.0.4 on 2022-07-05 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationalUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Nombre')),
                ('region', models.CharField(blank=True, choices=[('N', 'Norte'), ('CN', 'Centro Norte'), ('C', 'Centro'), ('S', 'Sur')], max_length=2, null=True)),
                ('municipality', models.CharField(blank=True, max_length=50, null=True, verbose_name='Municipio')),
                ('locality', models.CharField(blank=True, max_length=50, null=True, verbose_name='Localidad')),
                ('email', models.CharField(blank=True, max_length=50, null=True, verbose_name='Correo')),
                ('phone', models.CharField(blank=True, max_length=10, null=True, verbose_name='Telefono')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('status', models.BooleanField(default=True, verbose_name='Estatus')),
            ],
        ),
        migrations.AlterField(
            model_name='university',
            name='email',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Correo'),
        ),
        migrations.AlterField(
            model_name='university',
            name='locality',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Localidad'),
        ),
        migrations.AlterField(
            model_name='university',
            name='municipality',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Municipio'),
        ),
        migrations.AlterField(
            model_name='university',
            name='name',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Nombre'),
        ),
    ]
