# Generated by Django 4.0.4 on 2022-09-12 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0002_organizationalunit_alter_university_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='university',
            name='acronym',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Siglas'),
        ),
    ]
