# Generated by Django 4.0.4 on 2022-10-26 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0004_organizationalunit_acronym'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationalunit',
            name='key_code',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Clave'),
        ),
        migrations.AddField(
            model_name='university',
            name='key_code',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Clave'),
        ),
    ]
