# Generated by Django 4.0.4 on 2022-10-26 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0005_organizationalunit_key_code_university_key_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationalunit',
            name='email',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Correo'),
        ),
        migrations.AlterField(
            model_name='organizationalunit',
            name='locality',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Localidad'),
        ),
        migrations.AlterField(
            model_name='organizationalunit',
            name='municipality',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Municipio'),
        ),
        migrations.AlterField(
            model_name='organizationalunit',
            name='name',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Nombre'),
        ),
    ]
