# Generated by Django 4.0.4 on 2022-10-31 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0006_alter_organizationalunit_email_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organizationalunit',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='university',
            options={'ordering': ('name',)},
        ),
    ]
