# Generated by Django 4.0.4 on 2022-11-08 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0007_alter_organizationalunit_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='university',
            name='type',
            field=models.CharField(blank=True, choices=[('PREESC', 'Preescolar'), ('PRIM', 'Primaria'), ('SEC', 'Secundaria'), ('P', 'Preparatoria'), ('U', 'Universidad')], max_length=6, null=True),
        ),
    ]
